apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oslo-ingress
  namespace: oslo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: oslo-web-service
          servicePort: 80
        path: /
      - backend:
          serviceName: oslo-products-service
          servicePort: 80
        path: /api/products/(.*)
      - backend:
          serviceName: oslo-user-service
          servicePort: 80
        path: /api/users/(.*)
