kind: Service
apiVersion: v1
metadata:
  name: oslo-ingress-nginx
  namespace: oslo
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oslo-ingress
  namespace: oslo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: oslo-web-service
          servicePort: 80
        path: /
      - backend:
          serviceName: oslo-products-service
          servicePort: 80
        path: /api/products/*
      - backend:
          serviceName: oslo-user-service
          servicePort: 80
        path: /api/user/*
